/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/build": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Draws an image based on drawing commands
         * @description Creates an image with the specified dimensions and applies a series of drawing commands in order.
         *     Returns the generated image as a PNG.
         */
        post: operations["generate_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/commands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available command types
         * @description Returns a list of all available drawing command types with their metadata.
         */
        get: operations["get_command_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check server health
         * @description This endpoint just reutrns 'ok'
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Color
         * @description RGBA color with values from 0-255
         */
        Color: {
            /**
             * Format: int32
             * @description Alpha channel (0-255, where 255 is fully opaque)
             */
            a: number;
            /**
             * Format: int32
             * @description Blue channel (0-255)
             */
            b: number;
            /**
             * Format: int32
             * @description Green channel (0-255)
             */
            g: number;
            /**
             * Format: int32
             * @description Red channel (0-255)
             */
            r: number;
        };
        CommandTypeInfo: {
            /** @description Description of what this command does */
            description: string;
            /** @description List of required fields for this command */
            fields: string[];
            /** @description Human-readable label for the command */
            label: string;
            /** @description The command type identifier */
            value: string;
        };
        CommandTypesResponse: {
            commands: components["schemas"]["CommandTypeInfo"][];
        };
        /** DrawCommand */
        DrawCommand: {
            /** @description Fill color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description Height of the rectangle
             */
            height: number;
            /** @enum {string} */
            type: "filled_rect";
            /**
             * Format: int32
             * @description Width of the rectangle
             */
            width: number;
            /**
             * Format: int32
             * @description X coordinate of the top-left corner
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate of the top-left corner
             */
            y: number;
        } | {
            /** @description Outline color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description Height of the rectangle
             */
            height: number;
            /**
             * Format: int32
             * @description Thickness of the outline
             */
            thickness: number;
            /** @enum {string} */
            type: "stroke_rect";
            /**
             * Format: int32
             * @description Width of the rectangle
             */
            width: number;
            /**
             * Format: int32
             * @description X coordinate of the top-left corner
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate of the top-left corner
             */
            y: number;
        } | {
            /** @description Fill color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description Height of the rectangle
             */
            height: number;
            /**
             * Format: int32
             * @description Corner radius
             */
            radius: number;
            /** @enum {string} */
            type: "rounded_filled_rect";
            /**
             * Format: int32
             * @description Width of the rectangle
             */
            width: number;
            /**
             * Format: int32
             * @description X coordinate of the top-left corner
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate of the top-left corner
             */
            y: number;
        } | {
            /** @description Outline color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description Height of the rectangle
             */
            height: number;
            /**
             * Format: int32
             * @description Corner radius
             */
            radius: number;
            /**
             * Format: int32
             * @description Thickness of the outline
             */
            thickness: number;
            /** @enum {string} */
            type: "rounded_stroke_rect";
            /**
             * Format: int32
             * @description Width of the rectangle
             */
            width: number;
            /**
             * Format: int32
             * @description X coordinate of the top-left corner
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate of the top-left corner
             */
            y: number;
        } | {
            /** @description Fill color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description X coordinate of the center
             */
            cx: number;
            /**
             * Format: int32
             * @description Y coordinate of the center
             */
            cy: number;
            /**
             * Format: int32
             * @description Radius of the circle
             */
            radius: number;
            /** @enum {string} */
            type: "filled_circle";
        } | {
            /** @description Outline color */
            color: components["schemas"]["Color"];
            /**
             * Format: int32
             * @description X coordinate of the center
             */
            cx: number;
            /**
             * Format: int32
             * @description Y coordinate of the center
             */
            cy: number;
            /**
             * Format: int32
             * @description Radius of the circle
             */
            radius: number;
            /**
             * Format: int32
             * @description Thickness of the outline
             */
            thickness: number;
            /** @enum {string} */
            type: "stroke_circle";
        } | {
            /** @description Text color */
            color: components["schemas"]["Color"];
            /**
             * Format: float
             * @description Font size in pixels
             */
            font_size: number;
            /** @description Text content to render */
            text: string;
            /** @enum {string} */
            type: "text";
            /**
             * Format: int32
             * @description X coordinate of the text baseline
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate of the text baseline
             */
            y: number;
        } | {
            /** @description Pixel color */
            color: components["schemas"]["Color"];
            /** @enum {string} */
            type: "pixel";
            /**
             * Format: int32
             * @description X coordinate
             */
            x: number;
            /**
             * Format: int32
             * @description Y coordinate
             */
            y: number;
        };
        ImageRequest: {
            background?: null | components["schemas"]["Color"];
            commands: components["schemas"]["DrawCommand"][];
            /** Format: int32 */
            height: number;
            /** Format: int32 */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_image: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageRequest"];
            };
        };
        responses: {
            /** @description Image generated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": unknown;
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_command_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of available command types */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandTypesResponse"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
}
